{
 "cells": [
  {
   "cell_type": "code",
   "id": "initial_id",
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2025-12-13T16:21:06.830735Z",
     "start_time": "2025-12-13T16:21:06.815316Z"
    }
   },
   "source": [
    "\"\"\"\n",
    "Simplified Data Processing Script\n",
    "---------------------------------\n",
    "This script prepares a unified fruit freshness dataset and builds\n",
    "training/validation/test generators for model training.\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "import os\n",
    "from pathlib import Path\n",
    "import subprocess\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "\n",
    "BASE_PATH = Path.cwd()\n",
    "print(f\"BASE_PATH: {BASE_PATH}\")\n",
    "\n",
    "\n",
    "\n",
    "# Each fruit maps to its rotten and fresh classes in the original dataset.\n",
    "FRUIT_CATEGORIES = {\n",
    "    \"avocado\": {\n",
    "        \"rotten\": [\"Avocado Black 2\", \"Avocado ripe 3\"],\n",
    "        \"fresh\": [\"Avocado 1\", \"Avocado Black 1\", \"Avocado Green 1\"],\n",
    "    },\n",
    "    \"nut\": {\n",
    "        \"rotten\": [\"Nut 1\", \"Nut 4\", \"Nut 5\", \"Nut Pecan 1\"],\n",
    "        \"fresh\": [\"Nut 2\", \"Nut 3\", \"Nut Forest 1\"],\n",
    "    },\n",
    "    \"plum\": {\"rotten\": [\"Plum 3\", \"Plum 4\"], \"fresh\": [\"Plum 1\", \"Plum 2\"]},\n",
    "    \"peach\": {\n",
    "        \"rotten\": [\"Peach 3\", \"Peach 4\", \"Peach 5\", \"Peach 6\"],\n",
    "        \"fresh\": [\"Peach 1\", \"Peach 2\", \"Peach Flat 1\"],\n",
    "    },\n",
    "    \"cactus\": {\n",
    "        \"rotten\": [\"Cactus fruit green 1\"],\n",
    "        \"fresh\": [\"Cactus fruit 1\", \"Cactus fruit red 1\"],\n",
    "    },\n",
    "}\n",
    "\n",
    "\n",
    "\n",
    "ORIGINAL_DATASET_PATH = os.path.join(BASE_PATH, 'fruits-360-100x100')\n",
    "OUTPUT_PATH = os.path.join(BASE_PATH, 'multi_fruit_freshness_dataset')\n",
    "\n",
    "TRAIN_DIR = os.path.join(OUTPUT_PATH, 'Training')\n",
    "TEST_DIR = os.path.join(OUTPUT_PATH, 'Test')\n",
    "\n",
    "DATA_CONFIG_FILE = 'data_config.pkl'\n",
    "GENERATORS_INFO_FILE = 'generators_info.pkl'\n",
    "\n",
    "IMG_SIZE = (100, 100)\n",
    "BATCH_SIZE = 32\n",
    "VALIDATION_SPLIT = 0.2\n",
    "\n",
    "\n",
    "def ensure_dataset_exists():\n",
    "    \"\"\"\n",
    "    Ensures the original dataset exists.\n",
    "    If missing clone from git\n",
    "    \"\"\"\n",
    "    if Path(ORIGINAL_DATASET_PATH).exists():\n",
    "        print(f\"Dataset found at: {ORIGINAL_DATASET_PATH}\")\n",
    "        return True\n",
    "    else:\n",
    "        print(f\" Dataset not found at: {ORIGINAL_DATASET_PATH}\")\n",
    "        print(\" Cloning fruits-360 dataset...\")\n",
    "\n",
    "        try:\n",
    "            # Use subprocess to clone the repository\n",
    "            result = subprocess.run(\n",
    "                [\n",
    "                    \"git\",\n",
    "                    \"clone\",\n",
    "                    \"https://github.com/fruits-360/fruits-360-100x100.git\",\n",
    "                ],\n",
    "                cwd=BASE_PATH,  # Set working directory\n",
    "                capture_output=True,\n",
    "                text=True,\n",
    "            )\n",
    "\n",
    "            if result.returncode == 0:\n",
    "                print(f\"Dataset cloned successfully to: {ORIGINAL_DATASET_PATH}\")\n",
    "                return True\n",
    "            else:\n",
    "                print(f\"Failed to clone dataset. Error: {result.stderr}\")\n",
    "                return False\n",
    "\n",
    "        except Exception as e:\n",
    "            print(f\" Error cloning dataset: {e}\")\n",
    "            return False\n",
    "\n",
    "\n"
   ],
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BASE_PATH: D:\\foureYeare\\firistterm\\س417\\CS417_Project\n"
     ]
    }
   ],
   "execution_count": 1
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
